"""Modifying the user_id in Track model again

Revision ID: 1691fc8ae588
Revises: aaa932c36866
Create Date: 2024-07-12 20:44:09.553302

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1691fc8ae588'
down_revision = 'aaa932c36866'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('track', schema=None) as batch_op:
        batch_op.drop_constraint('fk_track_user_username', type_='foreignkey')
        batch_op.create_foreign_key(
            'fk_track_user', 'user', ['user_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('track', schema=None) as batch_op:
        batch_op.drop_constraint('fk_track_user', type_='foreignkey')
        batch_op.create_foreign_key('fk_track_user_username', 'user', [
                                    'user_id'], ['username'])

    # ### end Alembic commands ###
